### PR TITLE
Improve def handling and add test.

### LINKED ISSUE #29: Defining vars with def not properly supported
`((cr {} (def foo 42)))` throws an error: First argument to def must be a Symbol 

I have a local branch that fixes it by replacing `(-> ast :init :form)` for `(:name ast)` in `impl.cljc` and can open a PR. For `defn` it still throws an error though. There also should be tests added for `def`.

### PR DESCRIPTION
**Pull request by whilo**
Fixes #29. 

This does not work for `defn` yet and might need adjustments.

### CODE REVIEW

**Comment by leonoel** [comment]
On branch `def-handling`
I got `defn` to work. The problem was the `:arglists` `([,,,])` entry being passed as meta with the symbol returned by `:name` and being re-evaluated somehow, resulting in the vector being called as a function with zero argument.
Could you fix your test ? It looks like some part is missing

**Comment by whilo** [comment]
Sorry, missed a line somehow. Thanks for fixing the metadata! I can change the test if you want me to use `run`, I just need to first `defn` before testing it.

**Comment by leonoel** [comment]
Thank you !

**Comment by leonoel** [comment]
Released
* cloroutine `13`
* missionary `b.42`

**Pull request merged**
